In [7]:
from sklearn.cluster import KMeans
import numpy as np
import matplotlib.pyplot as plt

# Create some sample data
data = np.random.rand(100, 2)

# Specify the number of clusters (k)
k = 3

# Fit K-Means model
kmeans = KMeans(n_clusters=k)
kmeans.fit(data)

# Get cluster labels and centroids
labels = kmeans.labels_
centroids = kmeans.cluster_centers_


C:\Users\Sudarshan Ingole\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
C:\Users\Sudarshan Ingole\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


In [8]:
labels

array([0, 2, 2, 0, 0, 1, 0, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 2, 2, 0, 1,
       2, 2, 2, 0, 0, 2, 2, 1, 2, 1, 2, 1, 0, 2, 2, 2, 2, 0, 1, 2, 1, 2,
       1, 1, 0, 2, 2, 2, 2, 1, 1, 0, 2, 2, 2, 1, 0, 1, 2, 1, 0, 1, 1, 2,
       0, 1, 1, 0, 0, 0, 0, 2, 0, 1, 2, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 2])

In [9]:
centroids


array([[0.79063743, 0.38582284],
       [0.45805768, 0.81147335],
       [0.25017984, 0.29082996]])

In [11]:
from sklearn.cluster import MeanShift
import numpy as np

# Create some sample data
data = np.random.rand(100, 2)

# Fit Mean Shift model
meanshift = MeanShift()
labels = meanshift.fit_predict(data)


In [12]:
meanshift

MeanShift()

In [13]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [14]:
from sklearn.mixture import GaussianMixture
import numpy as np

# Create some sample data
data = np.random.rand(100, 2)

# Specify the number of clusters (k)
k = 3

# Fit Gaussian Mixture Model
gmm = GaussianMixture(n_components=k)
labels = gmm.fit_predict(data)


C:\Users\Sudarshan Ingole\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


In [15]:
gmm

GaussianMixture(n_components=3)

In [16]:
labels

array([1, 2, 2, 2, 0, 1, 1, 0, 2, 2, 1, 0, 1, 2, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 1, 1, 2, 2, 2, 0, 0, 2, 2, 2, 0, 2, 1, 2, 2, 0, 1, 2, 2,
       2, 0, 2, 0, 2, 0, 1, 2, 1, 2, 2, 1, 1, 2, 0, 2, 0, 0, 2, 0, 2, 0,
       0, 2, 1, 0, 2, 1, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 1, 0, 2, 0, 2,
       0, 0, 0, 2, 1, 1, 2, 2, 1, 0, 0, 0], dtype=int64)